# Generated by Django 4.2.4 on 2023-08-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(auto_created=True)),
                ("Product_name", models.CharField(max_length=50)),
                ("Product_Description", models.CharField(max_length=200)),
                (
                    "Produc_Condition",
                    models.CharField(
                        choices=[
                            ("1", "below average"),
                            ("2", "average"),
                            ("3", "good"),
                            ("4", "very good"),
                            ("5", "brand new"),
                        ],
                        max_length=10,
                    ),
                ),
                ("Upload_and_image", models.FileField(upload_to="")),
            ],
        ),
    ]
