# Generated by Django 4.2.4 on 2023-08-07 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_product_listing_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_id",
        ),
    ]
