# Generated by Django 4.2.4 on 2023-08-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_upload_and_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Upload_and_image",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
